### ISSUE TITLE
Add Vue example

### ISSUE THREAD

**Issue by anatolykopyl** [hood/vite-plugin-shadow-style#4]
I'm trying to get this working with Vue, but can't figure out how, since the entry file is so different.
All I get is a runtime error:
```
Uncaught ReferenceError: SHADOW_STYLE is not defined
```

**Comment by hood** [comment]
Could you please provide me with a link to a repository containing a repro? I’d have to do some guesswork to figure out your scenario, and I’m not sure that would lead to useful help from me.

**Comment by anatolykopyl** [comment]
Sure! I'm trying like this:
https://github.com/anatolykopyl/vue-shadow-style-repro

**Comment by hood** [comment]
I’ve just tried building the project, and it built with no issues. Where were you getting the error message mentioned above?

**Comment by hood** [comment]
Hi, I just wanted to let you know I’m still looking into this, I’m just not getting the chance of having too much spare time to work on this lately, but it’ll definitely get addressed.

**Comment by hood** [comment]
https://github.com/hood/vite-plugin-shadow-style/issues/5#issuecomment-1913770214
